#!/bin/bash
output=$(ls -p); output=$(sed -E 's/^([0-9])/\2\1/' <<< "$output"); output=$(LC_COLLATE=C sort -t '/' -k 2 <<< "$output"); output=$(sed -E 's/([0-9])([a-zA-Z])/\2\1/' <<< "$output"); echo -n "$output" | tr '\n' ','; echo
